import type {
  User,
  Member,
  Coach,
  GymClass,
  Product,
  Message,
} from './types'

// Current logged-in user (for demo purposes)
export const currentUser: User = {
  id: 'user-1',
  email: 'admin@ironforge.com',
  fullName: 'Alex Johnson',
  role: 'admin',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
}

// Coaches
export const coaches: Coach[] = [
  {
    id: 'coach-1',
    userId: 'user-2',
    fullName: 'Marcus Chen',
    email: 'marcus@ironforge.com',
    bio: 'Former professional bodybuilder with 15 years of coaching experience. Specializes in strength training and competition prep.',
    specializations: ['Strength Training', 'Bodybuilding', 'Powerlifting'],
    avatarUrl: 'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&h=400&fit=crop&crop=face',
    rating: 4.9,
    yearsExperience: 15,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'coach-2',
    userId: 'user-3',
    fullName: 'Sarah Williams',
    email: 'sarah@ironforge.com',
    bio: 'Certified yoga instructor and former Olympic gymnast. Brings a unique blend of flexibility and strength training.',
    specializations: ['Yoga', 'Flexibility', 'Core Training'],
    avatarUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop&crop=face',
    rating: 4.8,
    yearsExperience: 10,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'coach-3',
    userId: 'user-4',
    fullName: 'David Rodriguez',
    email: 'david@ironforge.com',
    bio: 'HIIT specialist and marathon runner. Helps clients achieve peak cardiovascular fitness and endurance.',
    specializations: ['HIIT', 'Cardio', 'Endurance Training'],
    avatarUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop&crop=face',
    rating: 4.7,
    yearsExperience: 8,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'coach-4',
    userId: 'user-5',
    fullName: 'Emily Foster',
    email: 'emily@ironforge.com',
    bio: 'Nutrition expert and functional fitness coach. Combines workout plans with personalized nutrition guidance.',
    specializations: ['Functional Fitness', 'Nutrition', 'Weight Loss'],
    avatarUrl: 'https://images.unsplash.com/photo-1609899517237-7a7c3a9c4a1c?w=400&h=400&fit=crop&crop=face',
    rating: 4.9,
    yearsExperience: 12,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
]

// Members
export const members: Member[] = [
  {
    id: 'member-1',
    fullName: 'James Miller',
    email: 'james@email.com',
    phone: '+1 555-0101',
    address: '123 Main St, New York, NY',
    postalCode: '10001',
    idNumber: 'ID-001234',
    idType: 'national_id',
    subscriptionStatus: 'active',
    subscriptionType: 'yearly',
    amountToPayCents: 99900,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-01-01'),
    ownerId: 'user-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member-2',
    fullName: 'Lisa Thompson',
    email: 'lisa@email.com',
    phone: '+1 555-0102',
    address: '456 Oak Ave, New York, NY',
    postalCode: '10002',
    idNumber: 'ID-001235',
    idType: 'passport',
    subscriptionStatus: 'active',
    subscriptionType: 'monthly',
    amountToPayCents: 9900,
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-07-01'),
    ownerId: 'user-1',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'member-3',
    fullName: 'Robert Garcia',
    email: 'robert@email.com',
    phone: '+1 555-0103',
    address: '789 Pine Rd, New York, NY',
    postalCode: '10003',
    idNumber: 'DL-98765',
    idType: 'drivers_license',
    subscriptionStatus: 'expired',
    subscriptionType: 'quarterly',
    amountToPayCents: 27900,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-04-01'),
    ownerId: 'user-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-04-02'),
  },
  {
    id: 'member-4',
    fullName: 'Emma Wilson',
    email: 'emma@email.com',
    phone: '+1 555-0104',
    address: '321 Elm St, New York, NY',
    postalCode: '10004',
    idNumber: 'ID-001236',
    idType: 'national_id',
    subscriptionStatus: 'pending',
    subscriptionType: 'monthly',
    amountToPayCents: 9900,
    startDate: new Date('2024-07-01'),
    ownerId: 'user-1',
    createdAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'member-5',
    fullName: 'Michael Brown',
    email: 'michael@email.com',
    phone: '+1 555-0105',
    address: '654 Cedar Ln, New York, NY',
    postalCode: '10005',
    idNumber: 'PP-456789',
    idType: 'passport',
    subscriptionStatus: 'active',
    subscriptionType: 'yearly',
    amountToPayCents: 99900,
    startDate: new Date('2024-03-15'),
    endDate: new Date('2025-03-15'),
    ownerId: 'user-1',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
]

// Classes
export const gymClasses: GymClass[] = [
  {
    id: 'class-1',
    name: 'Power Lifting Fundamentals',
    description: 'Learn the basics of powerlifting including squat, bench press, and deadlift with proper form and technique.',
    coachId: 'coach-1',
    coachName: 'Marcus Chen',
    dayOfWeek: 'Monday',
    startTime: '09:00',
    endTime: '10:30',
    maxCapacity: 12,
    currentEnrollment: 8,
    location: 'Weight Room A',
    level: 'beginner',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-2',
    name: 'Sunrise Yoga Flow',
    description: 'Start your day with an energizing yoga session combining breathwork and flowing movements.',
    coachId: 'coach-2',
    coachName: 'Sarah Williams',
    dayOfWeek: 'Tuesday',
    startTime: '06:00',
    endTime: '07:00',
    maxCapacity: 20,
    currentEnrollment: 15,
    location: 'Studio 1',
    level: 'all',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-3',
    name: 'HIIT Burn',
    description: 'High-intensity interval training designed to maximize calorie burn and improve cardiovascular fitness.',
    coachId: 'coach-3',
    coachName: 'David Rodriguez',
    dayOfWeek: 'Wednesday',
    startTime: '18:00',
    endTime: '19:00',
    maxCapacity: 25,
    currentEnrollment: 22,
    location: 'Main Floor',
    level: 'intermediate',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-4',
    name: 'Functional Fitness',
    description: 'Full-body workout focusing on movements that translate to everyday activities and sports performance.',
    coachId: 'coach-4',
    coachName: 'Emily Foster',
    dayOfWeek: 'Thursday',
    startTime: '12:00',
    endTime: '13:00',
    maxCapacity: 18,
    currentEnrollment: 12,
    location: 'Functional Area',
    level: 'all',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-5',
    name: 'Advanced Bodybuilding',
    description: 'Advanced techniques for muscle hypertrophy and competition preparation.',
    coachId: 'coach-1',
    coachName: 'Marcus Chen',
    dayOfWeek: 'Friday',
    startTime: '17:00',
    endTime: '19:00',
    maxCapacity: 10,
    currentEnrollment: 10,
    location: 'Weight Room B',
    level: 'advanced',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'class-6',
    name: 'Cardio Kickboxing',
    description: 'High-energy kickboxing workout combining martial arts techniques with cardio conditioning.',
    coachId: 'coach-3',
    coachName: 'David Rodriguez',
    dayOfWeek: 'Saturday',
    startTime: '10:00',
    endTime: '11:00',
    maxCapacity: 30,
    currentEnrollment: 18,
    location: 'Main Floor',
    level: 'intermediate',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Products
export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Premium Whey Protein',
    description: 'High-quality whey protein isolate with 25g protein per serving. Available in chocolate, vanilla, and strawberry.',
    priceCents: 5999,
    category: 'protein',
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    stock: 45,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-2',
    name: 'Creatine Monohydrate',
    description: 'Pure creatine monohydrate powder for increased strength and muscle recovery.',
    priceCents: 2999,
    category: 'supplements',
    imageUrl: 'https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&h=400&fit=crop',
    stock: 60,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-3',
    name: 'Monster Energy Green',
    description: 'Original Monster Energy drink for that extra boost during your workout.',
    priceCents: 399,
    category: 'energy_drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=400&h=400&fit=crop',
    stock: 120,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-4',
    name: 'Iron Forge Training Tee',
    description: 'Premium cotton blend training t-shirt with moisture-wicking technology.',
    priceCents: 3499,
    category: 'apparel',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
    stock: 35,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-5',
    name: 'Pre-Workout Ignite',
    description: 'Powerful pre-workout formula with caffeine, beta-alanine, and citrulline for maximum performance.',
    priceCents: 4499,
    category: 'supplements',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop',
    stock: 25,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-6',
    name: 'Lifting Straps',
    description: 'Heavy-duty lifting straps for improved grip during heavy lifts.',
    priceCents: 1999,
    category: 'accessories',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    stock: 50,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Messages
export const messages: Message[] = [
  {
    id: 'msg-1',
    senderId: 'coach-1',
    senderName: 'Marcus Chen',
    senderRole: 'coach',
    recipientId: 'member-1',
    recipientName: 'James Miller',
    subject: 'Training Program Update',
    content: 'Hi James, I have updated your training program for next month. Please check the new exercises and let me know if you have any questions. Looking forward to seeing your progress!',
    isRead: false,
    createdAt: new Date('2024-06-28T10:30:00'),
  },
  {
    id: 'msg-2',
    senderId: 'coach-2',
    senderName: 'Sarah Williams',
    senderRole: 'coach',
    recipientId: 'member-2',
    recipientName: 'Lisa Thompson',
    subject: 'Yoga Workshop This Weekend',
    content: 'Hi Lisa, Just a reminder about our special yoga workshop this Saturday. We will be focusing on advanced poses and meditation techniques. Please bring your own mat if possible.',
    isRead: true,
    createdAt: new Date('2024-06-27T14:15:00'),
  },
  {
    id: 'msg-3',
    senderId: 'user-1',
    senderName: 'Alex Johnson',
    senderRole: 'admin',
    recipientId: 'member-3',
    recipientName: 'Robert Garcia',
    subject: 'Membership Renewal Reminder',
    content: 'Dear Robert, We noticed your membership has expired. We would love to have you back! Contact us for special renewal offers available this month.',
    isRead: false,
    createdAt: new Date('2024-06-26T09:00:00'),
  },
  {
    id: 'msg-4',
    senderId: 'coach-4',
    senderName: 'Emily Foster',
    senderRole: 'coach',
    recipientId: 'member-5',
    recipientName: 'Michael Brown',
    subject: 'Nutrition Consultation Follow-up',
    content: 'Hi Michael, Great session yesterday! As discussed, I am attaching your personalized meal plan. Remember to track your meals this week and we will review progress next Monday.',
    isRead: true,
    createdAt: new Date('2024-06-25T16:45:00'),
  },
]
